name: iOS Unit Tests

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Run tests
        run: |
          xcodebuild test \
            -scheme PulseNews \
            -destination 'generic/platform=iOS Simulator' \
            -destination-timeout 60 \
            CODE_SIGNING_ALLOWED=NO
