name: iOS Unit Tests

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run tests
        run: |
          xcodebuild test \
            -scheme PulseNews \
            -destination 'platform=iOS Simulator,name=iPhone 17' \
            -destination-timeout 30 \
            CODE_SIGNING_ALLOWED=NO
